#define STATELED_DDR			DDRF
#define STATELED_PORT		PORTF
#define STATELED_PIN			PF1

#define FOTOSENSOR1_DDR		DDRF
#define FOTOSENSOR1_PORT	PORTF
#define FOTOSENSOR1_PIN		PF5

#define FOTOSENSOR2_DDR		DDRF
#define FOTOSENSOR2_PORT	PORTF
#define FOTOSENSOR2_PIN		PF7

#define PIRSENSOR1_DDR		DDRC
#define PIRSENSOR1_PORT		PORTC
#define PIRSENSOR1_PIND		PINC
#define PIRSENSOR1_PIN		PC0

#define PIRSENSOR2_DDR		DDRA
#define PIRSENSOR2_PORT		PORTA
#define PIRSENSOR2_PIND		PINA
#define PIRSENSOR2_PIN		PA7

#define DS1820_1_DDR			DDRC
#define DS1820_1_PORT		PORTC
#define DS1820_1_PIN			PC4

#define DS1820_2_DDR			DDRA
#define DS1820_2_PORT		PORTA
#define DS1820_2_PIN			PA3
